# Google ruby rules
inherit_gem:
  google-style: google-style.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - '**/lib/**/*'

# Exclude rubocop inheritance
inherit_mode:
  merge:
    - Exclude

# G Suite Ruby Samples rules
Metrics/BlockLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Style/WordArray:
  Enabled: false

Metrics/MethodLength:
  Max: 43
