language: ruby
dist: trusty
sudo: false
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
before_install:
  # https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - gem update --system
  - gem install bundler
  - gem install rubocop google-style
script:
  - rubocop
